from typing import Any, Iterator

class JSONObject:
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __len__(self) -> int: ...
    def items(self) -> Iterator[tuple[str, Any]]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self) -> Iterator[str]: ...
    def at_pointer(self, key: str) -> Any: ...
    def get_value(self) -> "JSONObject": ...
    def export(self) -> dict: ...
    def get_addr(self) -> int: ...

class JSONArray:
    def __contains__(self, item: Any) -> bool: ...
    def __getitem__(self, key: int) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def at_pointer(self, key: str) -> Any: ...
    def get_value(self) -> "JSONArray": ...
    def export(self) -> list: ...
    def get_addr(self) -> int: ...

class JSONElement:
    def at_pointer(self, key: str) -> "JSONElement": ...
    def get_value(self) -> Any: ...
    def export(self) -> Any: ...
    def get_addr(self) -> int: ...

class JSONParser:
    def __init__(self, max_capacity: int | None = None) -> None: ...
    def parse(self, event: bytes) -> JSONObject | JSONArray | JSONElement: ...
    def parse_in_place(self, event: bytes) -> JSONObject | JSONArray | JSONElement: ...
    def parse_string(self, event: str) -> JSONObject | JSONArray | JSONElement: ...
    def load(self, path: str) -> Any: ...
    def loads(self, content: str) -> Any: ...
    def active_implementation(self) -> str: ...

def addr_to_element(element_addr: int) -> JSONObject | JSONArray | JSONElement: ...

MAXSIZE_BYTES: int
PADDING: int
SIMDJSON_VERSION: str
